name: "Dependabot Changesets"

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

jobs:
  changeset:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: hmarr/debug-action@v3.0.0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Add changeset
        uses: StafflinePeoplePlus/dependabot-changesets@v0.1.5
        with:
          owner: ${{ github.repository_owner }}
          repo: ui
          pr-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}